spring.application.name=Task-Collab
server.port=8080
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TaskSys
spring.datasource.username=sa
spring.datasource.password=310#sa#pw
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect

