spring.application.name=Task-Collab
server.port=8080

# SQL Server Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TaskSys;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password="310#sa#pw"
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create  # Change to 'validate' for production
spring.jpa.show-sql= true 
spring.jpa.properties.hibernate.format_sql=true  # Format SQL for easier reading

# JWT Configuration
jwt.secret=YourSuperSecretKey123!  # Keep this secure!
jwt.expirationMs=86400000  # 24 hours
